-- Seeding users
INSERT INTO users (userName, password, fullName, role, email, phoneNumber, imagePath)
VALUES ('ahmad', '123', 'Ahmad', 'ADMIN', 'ahmad@gmail.com', '123456789',
        'com/example/libraryManagementSystem/images/default.png'),
       ('ali', '123', 'Ali', 'ADMIN', 'ali@gmail.com', '123456789',
        'com/example/libraryManagementSystem/images/default.png'),
       ('sara', '123', 'Sara', 'LIBRARIAN', 'Sara@gmail.com', '123456789',
        'com/example/libraryManagementSystem/images/default.png'),
       ('nada', '123', 'Nada', 'USER', 'nada@gmail.com', '123456789',
        'com/example/libraryManagementSystem/images/default.png');

-- Seeding books
INSERT INTO books (title, author, dateOfPublication, ISBN, language, category, publisher, imagePath, pagesNumber,
                   copiesNumber)
VALUES ('The Great Gatsby', 'F. Scott Fitzgerald', '1925', '34556545', 'English', 'Literature', 'Scribner',
        'com/example/libraryManagementSystem/images/book.png', 180, 5),
       ('To Kill a Mockingbird', 'Harper Lee', '1960', '876456', 'English', 'Literature', 'J. B. Lippincott & Co.',
        'com/example/libraryManagementSystem/images/book.png', 281, 3),
       ('1984', 'George Orwell', '1949', '453554', 'English', 'Science Fiction', 'Secker & Warburg',
        'com/example/libraryManagementSystem/images/book.png',
        328, 2),
       ('Pride and Prejudice', 'Jane Austen', '1813', '53453245', 'English', 'Literature', 'T. Egerton, Whitehall',
        'com/example/libraryManagementSystem/images/book.png', 279, 4),
       ('The Catcher in the Rye', 'J. D. Salinger', '1951', '7574222', 'English', 'Literature',
        'Little, Brown and Company', 'com/example/libraryManagementSystem/images/book.png', 234, 6),
       ('الأرض', 'علي الطنطاوي', '2021', '87453454', 'Arabic', 'Science', 'المكتبة العصرية',
        'com/example/libraryManagementSystem/images/book.png', 200,
        10),
       ('Der Vorleser', 'Bernhard Schlink', '1995', '2378765', 'German', 'Literature', 'Diogenes',
        'com/example/libraryManagementSystem/images/book.png',
        300, 7),
       ('L\Étranger', 'Albert Camus', '1942', '237654', 'French', 'Literature', 'Gallimard',
        'com/example/libraryManagementSystem/images/book.png', 250,
        8),
       ('La Peste', 'Albert Camus', '1947', '2376545', 'French', 'Literature', 'Gallimard',
        'com/example/libraryManagementSystem/images/book.png', 300, 6),
       ('Les Misérables', 'Victor Hugo', '1862', '23765454', 'French', 'Literature', 'A. Lacroix, Verboeckhoven & Cie',
        'com/example/libraryManagementSystem/images/book.png', 500, 4),
       ('Don Quixote', 'Miguel de Cervantes', '1605', '237654543', 'Spanish', 'Literature', 'Francisco de Robles',
        'com/example/libraryManagementSystem/images/book.png', 400, 9),
       ('El amor en los tiempos del cólera', 'Gabriel García Márquez', '1985', '237654543', 'Spanish', 'Literature',
        'Oveja Negra', 'com/example/libraryManagementSystem/images/book.png', 400, 9),
       ('Mathematics for the Nonmathematician', 'Morris Kline', '1967', '23765454435', 'English', 'Math',
        'Dover Publications', 'com/example/libraryManagementSystem/images/book.png', 400, 9),
       ('A Peoples History of the United States', 'Howard Zinn', '1980', '43645433', 'English', 'History',
        'Harper & Row',
        'com/example/libraryManagementSystem/images/book.png', 400, 9),
       ('العرب والعالم', 'عبد العزيز الدريوش', '2010', '76532432', 'Arabic', 'History', 'المكتبة العصرية',
        'com/example/libraryManagementSystem/images/book.png', 400, 9),
       ('The Hobbit', 'J.R.R. Tolkien', '1937', '978-0-345-3968-3', 'English', 'Fantasy', 'George Allen & Unwin',
        'com/example/libraryManagementSystem/images/book.png', 310, 5),
       ('The Lord of the Rings', 'J.R.R. Tolkien', '1954', '978-24022-1', 'English', 'Fantasy', 'George Allen & Unwin',
        'com/example/libraryManagementSystem/images/book.png', 1000, 2),
       ('The Silmarillion', 'J.R.R. Tolkien', '1977', '978-0-34581-4', 'English', 'Fantasy', 'George Allen & Unwin',
        'com/example/libraryManagementSystem/images/book.png', 365, 3),
       ('The History of the Decline and Fall of the Roman Empire', 'Edward Gibbon', '1776', '978-0345-24022-1',
        'English', 'History', 'Strahan & Cadell', 'com/example/libraryManagementSystem/images/book.png', 365, 3),
       ('The War of the Worlds', 'H.G. Wells', '1898', '978-0-324022-1', 'English', 'Science Fiction',
        'William Heinemann', 'com/example/libraryManagementSystem/images/book.png', 365, 3),
       ('The Origin of Species', 'Charles Darwin', '1859', '978-0-345-242-1', 'English', 'Science', 'John Murray',
        'com/example/libraryManagementSystem/images/book.png', 365, 3),
       ('The Elements', 'Euclid', '300 BC', '978-0-345-24022-1', 'English', 'Math', 'John Murray',
        'com/example/libraryManagementSystem/images/book.png',
        365, 3),
       ('The Divine Comedy', 'Dante Alighieri', '1320', '978-0-35-24022-1', 'Italian', 'Literature', 'John Murray',
        'com/example/libraryManagementSystem/images/book.png', 365, 3),
       ('The Selfish Gene', 'Richard Dawkins', '1976', '97-0-345-24022-1', 'English', 'Science',
        'Oxford University Press', 'com/example/libraryManagementSystem/images/book.png', 365, 3);